server:
  port: 8080
  servlet:
    context-path: /api

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/testapp_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test_user
    password: test_user_password
